# Generated by Django 3.2.20 on 2024-02-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('latitude', models.TextField(blank=True, default='', null=True)),
                ('longitude', models.TextField(blank=True, default='', null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('device_token', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LonLat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('latitude', models.TextField(blank=True, default='', null=True)),
                ('longitude', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('latitude', models.TextField(blank=True, default='', null=True)),
                ('longitude', models.TextField(blank=True, default='', null=True)),
                ('device_id', models.TextField(blank=True, default='', null=True)),
                ('device_token', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
                ('verification', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Done')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_link', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
            ],
        ),
    ]
